routes/web.php
<?php

use Illuminate\Http\Request;
use App\Models\Article;
use App\Conversation;
use App\User;
use App\Models\Autority;

use App\Models\Questions;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){

	// dd()
	 
	 // rescue(function(){

			if(auth()->check()){
				return redirect(url('/').'/home');
			}

			$lawyers=User::orderBy('created_at','desc')->orderBy('updated_at','desc')->simplePaginate(4);
			$specialities=App\Models\Speciality::orderBy('name','asc')->get();
			$articles=Article::orderBy('created_at','desc')->where('state','PUT_ON_LINE')->simplePaginate(4);

			return view('papers',compact('articles','specialities','lawyers'));
			
	 // });
	
});


// Route::get('/register',function(){
// 	return view('registers');
// });



Route::post('/test/ajax',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->mtype == 'MESSAGE_TEXT')
		{
			$conversation=Conversation::create([
					'message'=> $request->message,
					'sender_type'=>'client',
					'message_type'=>'MESSAGE_TEXT',
					'consulting_id'=>(int) $request->cid,
					'user_id'=>(int) $request->uid
				]);

			return response()->json(['isSend'=>true,'conv'=>$conversation->id]);
		}else{


		}
		return response()->json(['données'=>$request->all()]);
});


Route::get('/test/message',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->ajax())
		{
			return response()->json([
				'isSend'=>true,
				'conv'=>session()->get('client')->Consulting()->first()->messages()->get()->last()->id,
				'message'=> session()->get('client')->Consulting()->first()->messages()->get()->last()
			]);
		}
});


Route::get('/faq','QuestionController@faq');

Route::get('/question/create','QuestionController@create')->name('question');


Route::get('/question/show/{id}','QuestionController@show')->name('faq');

Route::get('/follow',function(){
	return view('lawyer.consulting.follow');
});

// Route::get('/documents','DocumentController@index',function(){
// 	return 'charment des documents';
// });

Route::get('/docs','DocumentController@index')->name('document.index');

Route::post('/checkout','ConsultingController@checkout')->name('checkout');

Route::get('/client/infolow','ConsultingController@infollow')->name('infollow');

Route::post('/store','QuestionController@store')->name('save');

Route::post('/test',function(Request $request){
	dd($request->all());
});

Route::post('/help/save','QuestionController@store')->name('help.save');

Route::group(['prefix'=>'avocat','middelware'=>['auth',
								  'AccountCheck']],function(){
	Route::get('/checkout','HomeController@checkout')->name('lwck');

	Route::get('/paymentCheckout','PaymentCheckout@index');

	Route::get('settings/profession','SettingsController@profession')->name('profession');

	Route::get('/article/delete/{id}','ArticleController@delete')->name('delete');

	Route::resources(['article'=>'ArticleController']);


	Route::resources(['autority'=>'AutorityController']);
	Route::resources(['sms'=>'SubscriptionSmsController']);
	// Route::get('/sms','SubscriptionSms@subscribe');

	Route::resources(['profile'=>'ProfileController']);

	Route::resources(['setting'=>'SettingsController']);

	Route::resources(['notification'=>'NotificationController']);


	// Route::resources(['consulting'=>'ConsultingController']);
	Route::post('/consulting/apply','ConsultingController@apply')->name('apply');

	Route::get('/consulting/treating/{id}','ConsultingController@treating')->name('treating');

	Route::post('/avocat/article/apply','ArticleController@redirect_by_action')->name('byaction');
	Route::post('/avocat/article/update_article','ArticleController@update_article')
				->name('update');
	Route::get('/question/','QuestionController@index')->name('response');

	// Route::resources(['question'=>'QuestionController']);

	Route::post('/question/response','QuestionController@response')->name('provide-answers');


	Route::get('/question/answers/{id}','QuestionController@answers')->name('answers');

	Route::get('/help/','ConsultingController@index')->name('help');

	Route::post('/help/save','ConsultingController@save')->name('save');


	Route::post('/active','HomeController@active')->name('active');


});

Route::group(['prefix'=>'admin'],function(){
		Route::get('/account','RootController@checklist')->name('checklist');
		Route::get('/allowed/{id}','RootController@allowed')->name('allowed');
		Route::get('/articles','RootController@articles')->name('articles');
		Route::resources(['document'=>'DocumentController']);
});

Route::post('/consulting/search','ConsultingController@search')->name('search');

Route::get('/consulting/send/{lawyer}','ConsultingController@send')->name('send');

Route::get('/consulting/create','ConsultingController@create')->name('create');

Route::get('/consulting/show/{id}','ConsultingController@show')->name('show');



Route::post('/consulting/store','ConsultingController@store')->name('store');


// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
	

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    //

    const NOTIFICATION_GAT_AWAY= 'NOTIFICATION_GAT_AWAY';

    const NOTIFICATION_POSSIBILITY=[
    	'NOTIFICATION_BY_SMS',
	    'NOTIFICATION_BY_MAIL',
	    'NOTIFICATION_IN_BOX'
    ];


    public $fillable=[
    	'TypeSetting','Value','user_id'
    ];
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Setting;

use App\User;

class SettingsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
         $this->middleware('AccountCheck');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }


    public function profession(Request $request)
    {
        return view('config.profession');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        // return view('lawyer.settings.notification');
        return view('lawyer.settings.config_notification');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'notification'=>'required'
        ]);

        $message='';
     
        // try
        // {
            switch ($request->notification) {
            case 0:
                

                if(!(auth()->user()->sms->last()->TotalSms > 0))
                {
                    session()->put(['message'=>'Veuillez recharger les sms à fin de béneficier de ce service']);
                    return back();
                }

                if(!(count(auth()->user()->setting()->where('TypeSetting',
                            Setting::NOTIFICATION_GAT_AWAY
                        )->first())))
                {
                               
                        Setting::create([
                                'TypeSetting'=>Setting::NOTIFICATION_GAT_AWAY,
                                'Value'     =>Setting::NOTIFICATION_POSSIBILITY[0],
                                'user_id'   =>auth()->user()->id
                        ]);
                        dd('message');

                        session()->put(['message'=>'Paramettre configuré avec succès']);

                        return back();
                }
                        
                        if(count(auth()->user()->setting()->where('TypeSetting',
                            Setting::NOTIFICATION_GAT_AWAY)) &&
                                !(auth()->user()->setting()->where('TypeSetting',
                                Setting::NOTIFICATION_GAT_AWAY
                            )->first()->Value == Setting::NOTIFICATION_POSSIBILITY[0])
                            )
                        {
                            auth()->user()->setting()->where('TypeSetting',
                                    Setting::NOTIFICATION_GAT_AWAY
                            )->first()->update(['Value'=>Setting::NOTIFICATION_POSSIBILITY[0]]);

                            session()->put(['message'=>'Configuration modifiée avec succès']);

                            return back();
                        }

                        session()->put(['message'=>'Ce paramettre a été déjà définit']);

                        return back();
                

                break;
            case 1:
                Setting::create([
                        'TypeSetting'=>Setting::NOTIFICATION_GAT_AWAY,
                        'Value'     =>Setting::NOTIFICATION_POSSIBILITY[1],
                        'user_id'   =>auth()->user()->id
                ]);

                session()->put(['message'=>'Paramettre configuré avec succès']);

                return back();
                break;
            case 2:
                Setting::create([
                        'TypeSetting'=>Setting::NOTIFICATION_GAT_AWAY,
                        'Value'     =>Setting::NOTIFICATION_POSSIBILITY[2],
                        'user_id'   =>auth()->user()->id
                ]);

                session()->put(['message'=>'Paramettre configuré avec succès']);

                return back();

                break;
            default:
               session()->put(['message'=>'Aucun paramettre trouvé']);

                return back();
                break;
        }
            

        // }catch(\Exception $e)
        // {

        // }
        // dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/lawyer/settings/config_notification.blade.php
@extends('layouts.admin')



@section('content')
	

	 <div class="row">
    	@include('inc.message')
    
  	</div>
	<div class="row">
		<div class="title_left">
	        <h3>&nbsp;&nbsp;Configuration des notifications </h3>
	    </div>
	</div>

	<div class="row">
              
              <div class="col-md-6 col-xs-12" >
                

                

                <div class="x_panel" style="border-top:3px solid #1b2254e3; ">
                  <div class="x_title">
                    <h2>Canal de notification <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p>
                      
                    </p>
                    <!-- start form for validation -->
                    <form id="demo-form" action="{{route('setting.store')}}" method="post" data-parsley-validate="" novalidate="">
                    	{{csrf_field()}}

               
                     <!--  <label for="fullname">Full Name * :</label>
                      <input type="text" id="fullname" class="form-control" name="fullname" required="">

                      <label for="email">Email * :</label>
                      <input type="email" id="email" class="form-control" name="email" data-parsley-trigger="change" required="">

                      <label>Gender *:</label> -->
                      <!-- <p>
                        M:
                        <div class="iradio_flat-green checked" style="position: relative;"><input type="radio" class="flat" name="gender" id="genderM" value="M" checked="" required="" data-parsley-multiple="gender" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div> F:
                        <div class="iradio_flat-green" style="position: relative;"><input type="radio" class="flat" name="gender" id="genderF" value="F" data-parsley-multiple="gender" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
                      </p>

                      <label>Hobbies (2 minimum):</label>
                      <p style="padding: 5px;">
                        <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" name="hobbies[]" id="hobby1" value="ski" data-parsley-mincheck="2" required="" class="flat" data-parsley-multiple="hobbies" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div> Skiing
                        <br>
 -->
                        <!-- <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" name="hobbies[]" id="hobby2" value="run" class="flat" data-parsley-multiple="hobbies" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div> Running
                        <br>

                        <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" name="hobbies[]" id="hobby3" value="eat" class="flat" data-parsley-multiple="hobbies" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div> Eating
                        <br>

                        <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" name="hobbies[]" id="hobby4" value="sleep" class="flat" data-parsley-multiple="hobbies" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div> Sleeping
                        <br>
                        </p><p>

                          <label for="heard">Heard us by *:</label>
                          <select id="heard" class="form-control" required="">
                            <option value="">Choose..</option>
                            <option value="press">Press</option>
                            <option value="net">Internet</option>
                            <option value="mouth">Word of mouth</option>
                          </select> -->

                          <!-- <label for="message">Message (20 chars min, 100 max) :</label> -->
                			<label>Moyen utilisé pour la réception de notification</label>
									<select name="notification" class="form-control">
										<option value="0">Réception par sms</option>
										<option value="1">Réception par mail</option>
										<option value="2">Réception en inbox(compte utilisateur)</option>
									</select>

							<br>
                          <button type="submit" class="btn btn-primary pull-right" style="background:#1b2254e3;border-radius:0;">Configurer</button>

                    <p></p></form>
                    <!-- end form for validations -->

                  </div>
                </div>


              </div>


            </div>




@stop


@section('title','configuration de service de notification')

resources/views/lawyer/settings/notification.blade.php
@extends('layouts.app')


@section('content')

	<div class="row">
			<div class="col-md-12">
				@if(session('message'))
					<h1>{{session('message')}}</h1>
					{{session()->put('message','')}}
				@endif
				<div class="col-md-8 col-md-offset-2">
					<div class="row">
						<div class="col-md-5">
							<div class="panel panel-default">
							<div class="panel-heading">
								<div class="panel-title">
									Configuration des paramèttres utilisateur
								</div>
							</div>
							<form  method="post" action="{{route('setting.store')}}">
								{{csrf_field()}}
								<div class="panel-body">
									<label>Moyen utilisé pour la réception de notification</label>
									<select name="notification" class="form-control">
										<option value="0">Réception par sms</option>
										<option value="1">Réception par mail</option>
										<option value="2">Réception en inbox(compte utilisateur)</option>
									</select>
								</div>
								<div class="panel-footer text-right">
									<button class="btn btn-primary" style="">Configurer</button>
								</div>
							</form>
						</div>
						</div>
					</div>
			</div>
		</div>
	</div>


@stop