routes/web.php
<?php

use Illuminate\Http\Request;
use App\Models\Article;
use App\Conversation;
use App\User;
use App\Models\Autority;

use App\Models\Questions;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){

	// dd()
	 
	 // rescue(function(){

			if(auth()->check()){
				return redirect(url('/').'/home');
			}

			$lawyers=User::orderBy('created_at','desc')->orderBy('updated_at','desc')->simplePaginate(4);
			$specialities=App\Models\Speciality::orderBy('name','asc')->get();
			$articles=Article::orderBy('created_at','desc')->where('state','PUT_ON_LINE')->simplePaginate(4);

			return view('papers',compact('articles','specialities','lawyers'));
			
	 // });
	
});


// Route::get('/register',function(){
// 	return view('registers');
// });



Route::post('/test/ajax',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->mtype == 'MESSAGE_TEXT')
		{
			$conversation=Conversation::create([
					'message'=> $request->message,
					'sender_type'=>'client',
					'message_type'=>'MESSAGE_TEXT',
					'consulting_id'=>(int) $request->cid,
					'user_id'=>(int) $request->uid
				]);

			return response()->json(['isSend'=>true,'conv'=>$conversation->id]);
		}else{


		}
		return response()->json(['données'=>$request->all()]);
});


Route::get('/test/message',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->ajax())
		{
			return response()->json([
				'isSend'=>true,
				'conv'=>session()->get('client')->Consulting()->first()->messages()->get()->last()->id,
				'message'=> session()->get('client')->Consulting()->first()->messages()->get()->last()
			]);
		}
});


Route::get('/faq','QuestionController@faq');

Route::get('/question/create','QuestionController@create')->name('question');


Route::get('/question/show/{id}','QuestionController@show')->name('faq');

Route::get('/follow',function(){
	return view('lawyer.consulting.follow');
});

// Route::get('/documents','DocumentController@index',function(){
// 	return 'charment des documents';
// });

Route::get('/docs','DocumentController@index')->name('document.index');

Route::post('/checkout','ConsultingController@checkout')->name('checkout');

Route::get('/client/infolow','ConsultingController@infollow')->name('infollow');

Route::post('/store','QuestionController@store')->name('save');

Route::post('/test',function(Request $request){
	dd($request->all());
});

Route::post('/help/save','QuestionController@store')->name('help.save');

Route::group(['prefix'=>'avocat','middelware'=>['auth',
								  'AccountCheck']],function(){
	Route::get('/checkout','HomeController@checkout')->name('lwck');

	Route::get('/paymentCheckout','PaymentCheckout@index');

	Route::get('settings/profession','SettingsController@profession')->name('profession');

	Route::get('/article/delete/{id}','ArticleController@delete')->name('delete');

	Route::resources(['article'=>'ArticleController']);


	Route::resources(['autority'=>'AutorityController']);
	Route::resources(['sms'=>'SubscriptionSmsController']);
	// Route::get('/sms','SubscriptionSms@subscribe');

	Route::resources(['profile'=>'ProfileController']);

	Route::resources(['setting'=>'SettingsController']);

	Route::resources(['notification'=>'NotificationController']);


	// Route::resources(['consulting'=>'ConsultingController']);
	Route::post('/consulting/apply','ConsultingController@apply')->name('apply');

	Route::get('/consulting/treating/{id}','ConsultingController@treating')->name('treating');

	Route::post('/avocat/article/apply','ArticleController@redirect_by_action')->name('byaction');
	Route::post('/avocat/article/update_article','ArticleController@update_article')
				->name('update');
	Route::get('/question/','QuestionController@index')->name('response');

	// Route::resources(['question'=>'QuestionController']);

	Route::post('/question/response','QuestionController@response')->name('provide-answers');


	Route::get('/question/answers/{id}','QuestionController@answers')->name('answers');

	Route::get('/help/','ConsultingController@index')->name('help');

	Route::post('/help/save','ConsultingController@save')->name('save');


	Route::post('/active','HomeController@active')->name('active');


});

Route::group(['prefix'=>'admin'],function(){
		Route::get('/account','RootController@checklist')->name('checklist');
		Route::get('/allowed/{id}','RootController@allowed')->name('allowed');
		Route::get('/articles','RootController@articles')->name('articles');
		Route::resources(['document'=>'DocumentController']);
});

Route::post('/consulting/search','ConsultingController@search')->name('search');

Route::get('/consulting/send/{lawyer}','ConsultingController@send')->name('send');

Route::get('/consulting/create','ConsultingController@create')->name('create');

Route::get('/consulting/show/{id}','ConsultingController@show')->name('show');



Route::post('/consulting/store','ConsultingController@store')->name('store');


// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
	

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //

    public $fillable=[
    	'title','Content','Slug','user_id'
    ];

    const ARTICLE_STATE=[
    	'DRAFT',
    	'PUT_ON_LINE'
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Article;

use Intervention\Image\Facades\Image;

use Illuminate\Support\Facades\Hash;

use Illuminate\Support\Carbon;

class ArticleController extends Controller
{

    public function __construct()
    {
        // $this->middleware('checkout');
        $this->middleware('auth')->except('show');
        $this->middleware('AccountCheck')->except('show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles=auth()->user()->articles()->get();

        $draft=0;
        $online=0;

        foreach ($articles as  $article) {
            if($article->state == 'DRAFT')
            {
                $draft++;
            }else
            {
                $online++;
            }
        }

        // $date=Carbon::parse('2018-07-01 09:15:47');
        // dd($date);
        return view('lawyer.article.liste_articles',compact('articles','draft','online'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lawyer.article.news_articles');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
        // dd($request->all()); 

        $this->validate($request,[
            'title'=>'required|max:500',
            'descr'=>'required',
            'tosendlike'=>'required|integer|min:1|max:2'
        ]);

        // try{

                if($request->file('file'))
                {
                    
                    $file = $request->file('file');

                    $fileOriginalName = pathinfo($file->getClientOriginalName());
                    $fileSize = $file->getSize();
                   
                    $p=public_path('img/upload/').$fileOriginalName['basename'];

                    if($request->file('file')
                               ->move(public_path('img/upload'),$p
                        )){
                        
                       

                        $request->file('file')->getClientOriginalName();
                        $article            = new Article();
                        $article->title     = $request->title;
                        $article->content   = $request->descr;
                        $article->slug      = str_slug($request->title,'-');
                        $article->created_at=Carbon::now();

                        switch ($request->tosendlike) {
                            case 1:
                                  $article->state= Article::ARTICLE_STATE[0];
                            break;
                            
                            case 2:
                                  $article->state= Article::ARTICLE_STATE[1];
                            break;
                        }

                        $article->cover          = $request->file('file')->getClientOriginalName();
              
                        $article->user_id        = auth()->user()->id;
                        $article->save();

                        $image=  Image::make($p);
                        $image->resize(512,380);
                        unlink($p);
                        $image->save();
                        // $picture = new Picture();
                        // $picture->Name = Hash::make($fileOriginalName['filename']).'.'.$fileOriginalName['extension'];
                        // $picture->profile_id = auth()->user()->profile->id;
                        // $picture->thumbnail = $newFileName;
                        // $picture->save();



                         session()->put('message','L\'article a été ajouté avec succès');
                         return redirect()->back();

                      }else{

                         session()->put('message','L\'article n\'a pas pu être ajouté pour de raison inentendue et nous vous garantissons que nous férons de notre mieux pour régler le problème, franche collaboration!');
                         return back();

                      }
                
                }else{

                    $article            = new Article();
                    $article->title     = $request->title;
                    $article->content   = $request->descr;
                    $article->slug      = str_slug($request->title,'-');
                    $article->created_at=Carbon::now();

                     switch ($request->tosendlike) {
                            case 1:
                                  $article->state=Article::ARTICLE_STATE[0];
                            break;
                            
                            case 2:
                                  $article->state=Article::ARTICLE_STATE[1];
                            break;
                        }

                    $article->user_id   =auth()->user()->id;
                    $article->save();

                    session()->put('message','L\'article a été ajouté avec succès');
                    return back();
                

               }

        // }catch(\Exception $e){

        // }
    
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        //

        // dd($id);
        $article=Article::where('id',$id)->get()[0];

        $recents=Article::all();

        return view('blog',compact('article','recents'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        if(!Article::find($id))
            return redirect(route('article.index'));

        $article=Article::find($id);
        // dd($article->id);
        return view('lawyer.article.edit_articles',compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

       
    }

    public function redirect_by_action(Request $request)
    {
        $this->validate($request,[
            'item'=>'required|integer',
            'action'=>'required|integer|max:2|min:1'
        ]);

        if(!Article::find($request->item))
                return back();
        switch ($request->action) {
            case 1:
                    Article::find($request->item)->delete();
                    session()->put('message','Suppression réusit avec succès');
                    return back();
                break;
                
            case 2:
                    return redirect(route('article.edit',['id'=>$request->item]));
                break;
        }

        // dd($request->all());
    }


    public function update_article(Request $request)
    {
        // dd($request->all()); 

        $this->validate($request,[
            'item'=>'required|integer',
            'title'=>'required|max:255',
            'tosendlike'=>'required|integer|min:1|max:2',
            'descr'=>'required'
        ]);

        if(!Article::find($request->item))
            return back();

        if($request->file('file'))
        {   
          

             if($request->file('file')
                               ->move(public_path('img/upload'),$request->file('file')
                               ->getClientOriginalName()
                        )){
                  // dd('modification');
                Article::where('id',(int)$request->item)
                    ->update([
                        'title'     =>$request->title,
                        'content'   =>$request->descr,
                        'state'     => $request->tosendlike == 1?Article::ARTICLE_STATE[0]:
                                       Article::ARTICLE_STATE[1],
                        'cover'     => $request->file('file')->getClientOriginalName()


                    ]);
                session()->put('message','L\'article a été modifié avec succès');
                dd('modification');
                return back();

            }else{
                dd('une erreur a été rencontrée');
                session()->put('message','L\'article n\'a pas pu être modifié pour des raisons inentendues et nous vous garantissons que nous férons de notre mieux pour régler le problème. Franche collaboration!');
                return back();
            }
        }

           
            $article= Article::where('id',(int)$request->item)->first();
            $article->title=$request->title;
            $article->content=$request->descr;
            $article->state=(int)$request->tosendlike == 1 ?Article::ARTICLE_STATE[0]:
                                                            Article::ARTICLE_STATE[1];
            $article->save();
   
            
            session()->put('message','L\'article a été modifié avec succès');

            return back();
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,Request $request)
    {
        return 'suppression';
        // dd($request->id);
    }

    public function delete($id)
    {
        if(!isset($id)){
            return back();
        }

        Article::find($id)->first()->delete();

        return back();

    }
}

resources/views/lawyer/article/add_article.blade.php
@extends('layouts.app')


@section('content')
		@include('inc.message')
		@if($errors->any())

		<div class="alert alert-danger">
			<ul>
				@foreach($errors->all() as $errors)

					<li>{{$errors}}</li>

				@endforeach
			</ul>
		</div>
		<div class="col-md-6 col-md-offset-3 ">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<div class="panel-title">
						<span>Ajouter un article</span>
					</div>
				</div>
				<form method="post" action="{{route('article.store')}}">
					<div class="panel-body">
						
							{{csrf_field()}}
							<div class="form-group>">
								<label class="label-control pull-left">Titre</label>	
									<input type="text" class="form-control" name="title">
							</div>

							<div class="form-group">
								<label class="control-label pull-left">Contenu de l'article</label>
									<textarea name="content" class="form-control">
									</textarea>
							</div>
					
					</div>
					<div class="panel-footer">
						<button type="submit" class="btn btn-success ">Ajouter l'article</button>
					</div>
					</form>	
				</div>

			</div>
		</div>
	</div>

@stop

resources/views/lawyer/article/list_of_articles.blade.php
@extends('layouts.app')


@section('content')
		@if(session('message'))
			<h1>{{session('message')}}</h1>
			{{session()->put('message','')}}
		@endif
		
		<div class="col-md-6 col-md-offset-3 ">
				<h1>Tous les articles <strong>{{count($articles)}}</strong></h1>

				@foreach($articles as $article)
					<h3>{{$article->title}}</h3>
					<p>{{$article->Content}}</p>
					<a href="{{route('article.show',['id'=>$article->id])}}" class="btn btn-default">lire la suite</a>
					<a href="{{route('delete',['id'=>$article->id])}}" class="btn btn-primary">Supprimer</a>

				@endforeach
		</div>
		

@stop

	

resources/views/lawyer/article/news_articles.blade.php
@extends('layouts.admin')



@section('content')
  <div class="row">
    @if($errors->any())
      @foreach($errors->all() as $error)
        <p>{{$error}}</p>
      @endforeach
    @endif
  </div>
    @include('inc.message')
    <form method="post" action="{{route('article.store')}}" enctype="multipart/form-data">  
      {{csrf_field()}}
		<div class="row">
			<div class="title_left">
                <h3>&nbsp;&nbsp;Rediger vos articles facilement </h3>
              </div>
		</div>
		<div class="clear-fix"></div>
		<div class="row" >
              <div class="col-md-6 col-xs-12">
                <div class="x_panel" style="border-top:3px solid #1b2254e3;">
                   <div class="x_title">
                    <h2>Ajouter une image en live  </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-info-circle"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div> 
                  <div class="x_content text-center">
                      <p>Cette une image servira de présentation à votre article.</p>
                    <br>
                   
                         <!-- <form class="form-horizontal form-label-left"> -->
                      <div class="col-md-9" id="image-panel">
                        
                      </div>
                      <div class="form-group">
                        
                        <div class="col-md-9 col-sm-12 col-xs-12">

                          <label class="img-default btn btn-default" for="image-live" style="background:#1b2254e3;color:#fff;">Ajouter une image <i class="fa fa-picture-o"></i>
                            <input type="file" name="file" class="form-control" id="image-live" placeholder="Default Input">
                          </label>
                        </div><br><br><br>
                       
                      </div>
                      
                      <!-- </form> -->
                    </div>

                    

                    
                  </div>
                </div>

                <div class="col-md-6 col-xs-12">
                <div class="x_panel" style="border-top: 3px solid #1b2254e3;">
                   <div class="x_title">
                    <h2>Enregistrer l'article comme </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-info-circle"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div> 
                  <div class="x_content ">
                    <p style="margin-left:3%;">Cette option indique où sera mis l'article après soumision.</p>
                    <br>
                   
                         <!-- <form class="form-horizontal form-label-left"> -->

                      <div class="form-group">
                        
                        
                        <div class="col-md-12 col-sm-9 col-xs-12 text-center">
                          <select name="tosendlike" class="form-control" required="required" style="">
                            <!-- <option >Publier comme</option> -->
                            <option value="1" selected="selected">Brouillon</option>
                            <option value="2">Mettre en ligne</option>
                          </select>
                        </div>
                      </div>
                      
                      <!-- </form> -->
                    </div>

                    

                    
                  </div>
                </div>

              </div>

              <div class="row" >
              <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                   <div class="x_title">
                   
                    <div class="clearfix"></div>
                  </div> 
                  <div class="x_content">
                    <p style="margin-left:1%;">Donnez du sens à votre article en lui donnant un titre</p>
                    <br>
                   
                         <!-- <form class="form-horizontal form-label-left"> -->

                      <div class="form-group">
                        
                        
                        <div class="col-md-12 col-sm-9 col-xs-12">
                         <input type="text" value="{{old('title')}}" required="required"  name="title" class="form-control" placeholder="donner un titre à l'article ici">
                        </div>
                      </div>
                      
                      <!-- </form> -->
                    </div>

                    

                    
                  </div>
                </div>

              </div>

              <div class="row">
              		<div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Décrivez votre article à ce niveau<small>(description)</small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-info-circle"></i></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                      </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                  <p>Laissez libre cours à votre imagination, et faites découvrir aux autres ce qu'il y a de mieux en vous à travers votre imagination.</p>
                  <div id="alerts"></div>
                  <div class="btn-toolbar editor" data-role="editor-toolbar" data-target="#editor-one">
                    <div class="btn-group">
                      <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="fa fa-font"></i><b class="caret"></b></a>
                      <ul class="dropdown-menu">
                      </ul>
                    </div>

                    <div class="btn-group">
                      <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li>
                          <a data-edit="fontSize 5">
                            <p style="font-size:17px">Huge</p>
                          </a>
                        </li>
                        <li>
                          <a data-edit="fontSize 3">
                            <p style="font-size:14px">Normal</p>
                          </a>
                        </li>
                        <li>
                          <a data-edit="fontSize 1">
                            <p style="font-size:11px">Small</p>
                          </a>
                        </li>
                      </ul>
                    </div>

                    <div class="btn-group">
                      <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                      <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                      <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                      <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
                    </div>

                    <div class="btn-group">
                      <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
                      <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
                      <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-dedent"></i></a>
                      <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
                    </div>

                    <div class="btn-group">
                      <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
                      <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
                      <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
                      <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
                    </div>

                    <div class="btn-group">
                      <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
                      <div class="dropdown-menu input-append">
                        <input class="span2" placeholder="URL" type="text" data-edit="createLink">
                        <button class="btn" type="button">Add</button>
                      </div>
                      <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
                    </div>

                    <div class="btn-group">
                      <a class="btn" title="Insert picture (or just drag &amp; drop)" id="pictureBtn"><i class="fa fa-picture-o"></i></a>
                      <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" value="{{old('file')}}">
                    </div>

                    <div class="btn-group">
                      <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
                      <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
                    </div>
                  </div>

                  <div id="editor-one" class="editor-wrapper placeholderText" style="overflow:hidden;" contenteditable="true"></div>

                  <textarea name="descr" id="descr" style="display:none;"></textarea>
                  
                  <br>
                  <div id="retype" style="display:none;">{{old('descr')}}</div>
                  <div class="ln_solid"></div>

                  <div class="form-group">
                    
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <input type="submit" style="background:#1b2254e3;" value="Publier" class="btn btn-primary">
                    </div>
                  </div>
                </div>
              </div>
            </div>


              </div>	

        </form>



@stop