routes/web.php
<?php

use Illuminate\Http\Request;
use App\Models\Article;
use App\Conversation;
use App\User;
use App\Models\Autority;

use App\Models\Questions;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',function(){

	// dd()
	 
	 // rescue(function(){

			if(auth()->check()){
				return redirect(url('/').'/home');
			}

			$lawyers=User::orderBy('created_at','desc')->orderBy('updated_at','desc')->simplePaginate(4);
			$specialities=App\Models\Speciality::orderBy('name','asc')->get();
			$articles=Article::orderBy('created_at','desc')->where('state','PUT_ON_LINE')->simplePaginate(4);

			return view('papers',compact('articles','specialities','lawyers'));
			
	 // });
	
});


// Route::get('/register',function(){
// 	return view('registers');
// });



Route::post('/test/ajax',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->mtype == 'MESSAGE_TEXT')
		{
			$conversation=Conversation::create([
					'message'=> $request->message,
					'sender_type'=>'client',
					'message_type'=>'MESSAGE_TEXT',
					'consulting_id'=>(int) $request->cid,
					'user_id'=>(int) $request->uid
				]);

			return response()->json(['isSend'=>true,'conv'=>$conversation->id]);
		}else{


		}
		return response()->json(['données'=>$request->all()]);
});


Route::get('/test/message',function(Request $request){

		if(!session()->get('client'))
		{
			return;
		}

		if($request->ajax())
		{
			return response()->json([
				'isSend'=>true,
				'conv'=>session()->get('client')->Consulting()->first()->messages()->get()->last()->id,
				'message'=> session()->get('client')->Consulting()->first()->messages()->get()->last()
			]);
		}
});


Route::get('/faq','QuestionController@faq');

Route::get('/question/create','QuestionController@create')->name('question');


Route::get('/question/show/{id}','QuestionController@show')->name('faq');

Route::get('/follow',function(){
	return view('lawyer.consulting.follow');
});

// Route::get('/documents','DocumentController@index',function(){
// 	return 'charment des documents';
// });

Route::get('/docs','DocumentController@index')->name('document.index');

Route::post('/checkout','ConsultingController@checkout')->name('checkout');

Route::get('/client/infolow','ConsultingController@infollow')->name('infollow');

Route::post('/store','QuestionController@store')->name('save');

Route::post('/test',function(Request $request){
	dd($request->all());
});

Route::post('/help/save','QuestionController@store')->name('help.save');

Route::group(['prefix'=>'avocat','middelware'=>['auth',
								  'AccountCheck']],function(){
	Route::get('/checkout','HomeController@checkout')->name('lwck');

	Route::get('/paymentCheckout','PaymentCheckout@index');

	Route::get('settings/profession','SettingsController@profession')->name('profession');

	Route::get('/article/delete/{id}','ArticleController@delete')->name('delete');

	Route::resources(['article'=>'ArticleController']);


	Route::resources(['autority'=>'AutorityController']);
	Route::resources(['sms'=>'SubscriptionSmsController']);
	// Route::get('/sms','SubscriptionSms@subscribe');

	Route::resources(['profile'=>'ProfileController']);

	Route::resources(['setting'=>'SettingsController']);

	Route::resources(['notification'=>'NotificationController']);


	// Route::resources(['consulting'=>'ConsultingController']);
	Route::post('/consulting/apply','ConsultingController@apply')->name('apply');

	Route::get('/consulting/treating/{id}','ConsultingController@treating')->name('treating');

	Route::post('/avocat/article/apply','ArticleController@redirect_by_action')->name('byaction');
	Route::post('/avocat/article/update_article','ArticleController@update_article')
				->name('update');
	Route::get('/question/','QuestionController@index')->name('response');

	// Route::resources(['question'=>'QuestionController']);

	Route::post('/question/response','QuestionController@response')->name('provide-answers');


	Route::get('/question/answers/{id}','QuestionController@answers')->name('answers');

	Route::get('/help/','ConsultingController@index')->name('help');

	Route::post('/help/save','ConsultingController@save')->name('save');


	Route::post('/active','HomeController@active')->name('active');


});

Route::group(['prefix'=>'admin'],function(){
		Route::get('/account','RootController@checklist')->name('checklist');
		Route::get('/allowed/{id}','RootController@allowed')->name('allowed');
		Route::get('/articles','RootController@articles')->name('articles');
		Route::resources(['document'=>'DocumentController']);
});

Route::post('/consulting/search','ConsultingController@search')->name('search');

Route::get('/consulting/send/{lawyer}','ConsultingController@send')->name('send');

Route::get('/consulting/create','ConsultingController@create')->name('create');

Route::get('/consulting/show/{id}','ConsultingController@show')->name('show');



Route::post('/consulting/store','ConsultingController@store')->name('store');


// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
	

resources/views/admin/articles.blade.php
@extends('layouts.admin')


@section('content')
  <div class="row">
    @include('inc.message')
    
  </div>
	<div class="row">
		<div class="title_left">
	        <h3>&nbsp;&nbsp;Gérer vos articles simplement et facilement </h3>
	    </div>
	</div>
	<div class="row">
		<div class="col-md-12 col-xs-12 hidden-xs ">
                <div class="x_panel" style="border-top:0;border-top:3px solid #1b2254e3; ">
                   <div class="x_title">
                   
                    <div class="clearfix"></div>
                  </div> 
                  <div class="x_content" style="height:33px; ">
                 <!--    <p style="margin-left:1%;">Donnez du sens à votre article en lui donnant un titre</p> -->
                    <!-- <br /> -->
                   
                         <form class="form-horizontal form-label-left">

                      <div class="form-group">
                        
                        
                        <div class="col-md-2 col-sm-9 col-xs-12" style="border-right:1px solid #ccc;">
                            Articles <span class="badge badge-success">{{count($articles)}}</span>
                        </div>
                       
                        
                      <!-- <div class="col-md-6 "> -->
                           <!-- <button class="btn btn-primary">Trier</button> -->
                           <!-- <div class="pull-right"> -->
              <!--                <div class="col-md-6 ">
                             <input type="text" class="form-control" name="" placeholder="Rechercher un article rapidement">
                           </div>
                            <div class="col-md-6">
                             <button class="btn btn-primary" style="border-radius:0;background:#1b2254e3;">Rechercher</button>
                           </div>
                           </div>
                      </div> -->

                      
                      </div>

                    </form>

                    
                  </div>
                </div>

              </div>
	</div>
	<div class="row">
			
			<div class="row" style=" ">
                <div class="col-md-12 col-sm-6 col-xs-12" style="padding-left:20px;padding-right:20px;">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Tous les articles <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <table class="table table-bordered table-hover">
                      <thead style="background:#1b2254e3;color:#fff;">
                        <tr>
                          <th>#</th>
                          <th>Titre</th>
                          <th>Alias</th>
                          <!-- <th>Déscription</th> -->
                          <!-- <th>Date de création</th> -->
                          <th>Status actuel</th>
                          <th>Action à appliquer</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <!-- <tr>
                          <th scope="row"><input type="checkbox" name=""></th>
                          <td>Mark</td>
                          <td>Otto</td>
                          <td>@mdo</td>
                          <td>Mark</td>
                          <td>
                            <select class="form-control">
                                <option>Brouillon</option>
                                <option>Publier</option>
                            </select>
                          </td>
                          <td>
                            <select class="form-control">
                                <option>Supprimer</option>
                                <option>Modifier</option>
                            </select>
                          </td>
                        </tr> -->
                        @foreach($articles as $article)
                          <form method="post" action="{{route('byaction')}}"> 
                            {{csrf_field()}}
                            <input type="hidden" name="item" value="{{$article->id}}">
                            <tr>
                              <td><input type="checkbox" name="" class="checked" value="checked"></td>
                              <td>{{$article->title}}</td>
                              <td>{{$article->slug}}</td>
                              <!-- <td>{{$article->content}}</td> -->
                              <!-- <td>{{"25/25/2013"}}</td> -->
                              <!-- <td>{{$article->title}}</td> -->
                              <!-- <td> -->
                              <td>
                                @switch($article->state)
                                  @case('DRAFT')
                                      {{'Brouillon'}}
                                    @break
                                  @case('PUT_ON_LINE')
                                      {{'Publié'}}
                                    @break
                                @endswitch
                              </td>
                              <td>
                              <select  name="action" class="form-control">
                                  <option value="1" >Supprimer</option>
                                  <!-- <option value="2" >Modifier</option> -->
                              </select>
                            </td>
                            <td>
                              <button class="btn btn-primary pull-right" style="background:#1b2254e3;border-radius:0; ">Appliquer</button>
                            </td>
                              <!-- </td> -->
                            </tr>
                          </form>
                        @endforeach
                        <!-- <tr>
                          <th scope="row"><input type="checkbox" name=""></th>
                          <td>Jacob</td>
                          <td>Thornton</td>
                          <td>@fat</td>
                          <td>Jacob</td>
                          <td>
                            <select class="form-control">
                                <option>Brouillon</option>
                                <option>Publier</option>
                            </select>
                          </td>
                          <td>
                             <select class="form-control">
                                <option>Supprimer</option>
                                <option>Modifier</option>
                            </select>
                          </td>
                        </tr>
                        <tr>
                          <th scope="row"><input type="checkbox" name=""></th>
                          <td>Larry</td>
                          <td>the Bird</td>
                          <td>@twitter</td>
                          <td>Larry</td>
                          <td>
                            <select class="form-control">
                                <option>Brouillon</option>
                                <option>Mettre en ligne</option>
                            </select>
                          </td>
                          <td>
                             <select class="form-control">
                                <option>Supprimer</option>
                                <option>Modifier</option>
                            </select>
                          </td>
                        </tr> -->
                      </tbody>
                    </table>
                    <hr>
                      {{$articles->links()}}
                  </div>
                </div>
              </div>
              </div>

	</div>


@stop

resources/views/admin/checklist.blade.php
@extends('layouts.admin',['dossier'=>count($inactived)])


@section('content')
<div class="row">
    <div class="col-md-12">
        @include('inc.message')
    </div>
</div>
	<div class="row">
		
		<div class="col-md-12 col-xs-12 hidden-xs ">
                <div class="x_panel" style="border-top:0;border-top:3px solid #1b2254e3; ">
                   <div class="x_title">
                   
                    <div class="clearfix"></div>
                  </div> 
                  <div class="x_content" style="height:33px; ">
                 <!--    <p style="margin-left:1%;">Donnez du sens à votre article en lui donnant un titre</p> -->
                    <!-- <br /> -->
                   
                         <form class="form-horizontal form-label-left">

                      <div class="form-group">
                        
                        <div class="col-md-2 col-sm-9 col-xs-12" style="border-right:1px solid #ccc;">
                            Dossiers <span class="badge badge-success">{{count($inactived)}}</span>
                        </div> 
                      <!--   <div class="col-md-2 col-sm-9 col-xs-12" style="border-right:1px solid #ccc;">
                            Traités <span class="badge badge-success">1</span>
                        </div>
                        <div class="col-md-2 col-sm-9 col-xs-12" style="border-right:1px solid #ccc;">
                            En attente <span class="badge badge-success">1</span>
                        </div>
 -->
                      <!-- <div class="col-md-6 "> -->
                           <!-- <button class="btn btn-primary">Trier</button> -->
                    <!--        <div class="pull-right">
                             <div class="col-md-6 ">
                             <input type="text" class="form-control" name="" placeholder="Rechercher un article rapidement">
                           </div>
                            <div class="col-md-6">
                             <button class="btn btn-primary" style="border-radius:0;background:#1b2254e3;">Rechercher</button>
                           </div>
                           </div>
                      </div> -->

                      
                      </div>

                    </form>

                    
                  </div>
                </div>

              </div>
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-6 col-xs-12" style="padding-right:20px;">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Tous les comptes à traiter<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <table class="table table-bordered table-hover">
                      <thead style="background:#1b2254e3;color:#fff;">
                        <tr>
                          <th>N°</th>
                          <!-- <th>Client</th> -->
                          <th>Noms</th>
                          <!-- <th>Explicatino du dossier</th> -->
                          <!-- <th>Date de création</th> -->
                          <!-- <th>Etat</th> -->
                          <th>Action à appliquer</th>
                         <!--  <th>Date de création</th>
                          <th>Status actuel</th> -->
                          <th>Activation du compte</th>
                        </tr>
                      </thead>
                      <tbody>

                    @foreach($inactived as $user)
                 
                        <tr>
                           <!-- <th scope="row"><input type="checkbox" name=""></th> -->
                           <th scope="row">{{$loop->iteration}}</th>
                          <td>{{ucfirst($user->profileOfLawyer()->first()->firstname.' '.$user->profileOfLawyer()->first()->name)}}</td>
                          <td>
                             <button type="button" class="btn btn-primary" style="background:#1b2254e3;color:#fff;border-radius:0;" data-toggle="modal" data-target=".{{$user->id}}">lire le dossier</button>
                                                <div class="modal fade {{$user->id}}" style="display:none;" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                                      <div class="modal-dialog modal-lg " role="document" style="
                                      border-radius:0;">
                                        <div class="modal-content" style="
                                      border-radius:0;" >
                                            <div class="modal-header" style="background:#1b2254e3;color:#fff;height:48px;line-height:48px;">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close" 
                                            ><span aria-hidden="true" style="color:#fff;">&times;</span></button>
                                            <h4 class="modal-title" id="gridSystemModalLabel" ">Explication du dossier</h4>
                                          </div>

                                          <div class="modal-body">
                                            <p>Dossier avocat</p>
                                                
                                            <hr>
                                            <div class="row">
                                              <div class="col-md-12 text-center">
                                                @if($user->profile->picture()->orderBy('id','desc')->first())

                                                         <img style="height:80px;" src="{{asset('img/upload/'.$user->profile->picture()->orderBy('id','desc')->first()->Name)}}" class="img-circle " style="" >
                                                      
                                                      @else

                                                    @switch((int) $user->profileOfLawyer()->first()->sexe)
                                                  @case(1)
                                                       <img style="height:20px;" src="{{asset('img/upload/avatar.jpg')}}" class="img-circle">
                                                      @break

                                                  @case(2)
                                                        <img style="height:20px;" src="{{asset('img/upload/f-default-profile.png')}}" class="img-circle">
                                                      @break
                                                 

                                              @endswitch  

                                                      @endif
                                              </div>
                                            </div> 
                                            <!-- <hr> -->
                                            <div class="row">
                                              <div class="col-md-6">
                                                  <h3>Identité</h3>
                                                  <hr style="width:35%;">
                                                  <h2>Nom:&nbsp;{{$user->profileOfLawyer()->first()->name}}</h2>  
                                                  <h3>Contact</h3>
                                                  <hr style="width:35%;">
                                                  <h2>Email:{{$user->email}}
                                                    <br>
                                                    Téléphone:{{$user->profileOfLawyer()->first()->phone}}</h2>
                                              </div>
                                              <div class="col-md-6">
                                                  <h3>Autres informations</h3>
                                                  <hr>
                                                  <h2 style="margin-top:5px;">Numero d'ordre:<br>{{$user->profileOfLawyer()->first()->numero_ordre}}</h2>  
                                                  <h2 style="margin-top:5px;">nom du barreau:<br>{{$user->profileOfLawyer()->first()->barreau}}</h2> 
                                                  <h2 style="margin-top:5px;">Date de prestation:<br>{{$user->profileOfLawyer()->first()->date_prestation}}</h2>  
                                                 <h2 style="margin-top:5px;">Avocat stagiaire ou inscrit au tableau:{{$user->profileOfLawyer()->first()->type_avocat}}</h2>  
                                                <h2 style="margin-top:5px;">Nom du cabinet:<br>{{$user->profileOfLawyer()->first()->nom_cabinet}}</h2>  
                                                
                                                  
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                          </td>
                         
                          <!-- <td>Traiter}</td> -->
                          <td><a  href="{{route('allowed',['id'=>$user->id])}}" class="btn btn-default" style="background:#1b2254e3;color:#fff;">Activer le compte&nbsp;<i class="fa fa-check"></i></a>
                          
                        </td>
                        </tr>



                    @endforeach
                    </table>

                  </div>
                </div>
              </div>
            
  </div>


                       

      
@stop

resources/views/admin/documents.blade.php
@extends('layouts.admin')



@section('content')
	
	 <div class="row">
    @include('inc.message')
    
  </div>
  <div class="row">
  	@if($errors->any())
  		<ul>
  			@foreach($errors->all() as $error)

  				<li>{{$error}}</li>

  			@endforeach
  		</ul>
  	@endif
  </div>	
	<div class="row">
		<div class="title_left">
	        <h3>&nbsp;&nbsp;Mettre en ligne un document </h3>
	    </div>
	</div>

	<div class="row">
              
              <div class="col-md-6 col-xs-12" >
                

                

                <div class="x_panel" style="border-top:3px solid #1b2254e3; ">
                  <div class="x_title">
                    <h2>Votre réponse <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p>
                      	
                    </p>
                    <!-- start form for validation -->
                    <form id="demo-form" action="{{route('document.store')}}" method="post" data-parsley-validate="" novalidate="" enctype="multipart/form-data">
                    	{{csrf_field()}}

                    		<div class="row">
                    			<div class="col-md-12">
                    				<label class="label-control">Titre du doocument</label>
                    				<input type="text" class="form-control" placeholder="ex:contrant de confidentialité" name="title">
                    			</div>
                    		</div>
                    		<div class="row">
                    			<div class="col-md-12">
                    				<label class="label-control">Couverture du document</label>
                    				<input type="file" class="form-control" placeholder="ex:contrant de confidentialité" name="cover">
                    			</div>
                    		</div>
                    		<div class="row">
                    			<div class="col-md-12">
                    				<label class="label-control">Document(pdf,word,autres)</label>
                    				<input type="file" class="form-control" placeholder="ex:contrant de confidentialité" name="document">
                    			</div>
                    		</div>

                          <br>
                          <button type="submit" class="btn btn-primary pull-right" style="background:#1b2254e3;border-radius:0;">Ajouter</button>

                    <p></p></form>
                    <!-- end form for validations -->

                  </div>
                </div>


              </div>


            </div>



@stop